#!/usr/bin/env python3
"""Generate build.ninja for the PS Vita port.

    python3 configure_vita.py                 # port shell only (boot, ROM check, diagnostics)
    python3 configure_vita.py --with-game     # + the decomp's C, from the build tree (setup.sh)
    ninja                                     # -> build/khdays-vita-<VERSION>.vpk

Game sources come from the build tree (the decomp with patches/decomp.patch applied), never
from this repository. What is compiled from it, and what the port replaces, is listed in
tools/decomp_sources.py.
"""
import argparse
import os
import shlex
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT / "tools"))

TITLE = "Kingdom Hearts 358/2 Days"
TITLE_ID = "KHDD00358"

VITASDK = Path(os.environ.get("VITASDK", Path.home() / "vitasdk"))
BIN = VITASDK / "bin"

# The game code is compiled for the Cortex-A9 in ARM mode. -fsigned-char and -fshort-enums off
# (int enums) follow mwccarm's settings in the decomp's configure.py (-char signed, -enum int),
# so structs keep the layout the original compiler gave them. gnu11: the decomp relies on
# unprototyped `extern int f();` declarations, which C23 would read as `f(void)`.
COMMON_CFLAGS = [
    "-mcpu=cortex-a9", "-mfpu=neon", "-marm", "-mfloat-abi=hard",
    "-fsigned-char", "-fno-short-enums", "-fno-strict-aliasing", "-fwrapv",
    "-ffunction-sections", "-fdata-sections", "-g",
    "-DPLATFORM_VITA=1",
]
PORT_CFLAGS = ["-std=gnu11", "-O3", "-Wall", "-Wno-unused-function"]
GAME_CFLAGS = [
    "-std=gnu11", "-O2", "-w",
    # The decomp's K&R-style calls and int<->pointer casts are deliberate: mwccarm accepted
    # them, and GCC 14+ turns these diagnostics into errors by default.
    "-Wno-error=implicit-function-declaration", "-Wno-error=int-conversion",
    "-Wno-error=incompatible-pointer-types", "-Wno-error=implicit-int",
    "-Wno-error=return-mismatch",
]

GAME_CXXFLAGS = ["-std=gnu++11", "-O2", "-w", "-fno-exceptions", "-fpermissive"]

LIBS = [
    "-lvitaGL", "-lvitashark", "-lSceShaccCgExt", "-lmathneon", "-lstdc++", "-lm", "-lc",
    "-lkubridge_stub_weak", "-ltaihen_stub", "-lSceShaccCg_stub", "-lSceKernelDmacMgr_stub",
    "-lSceCommonDialog_stub", "-lSceGxm_stub", "-lSceDisplay_stub", "-lSceAppMgr_stub",
    "-lSceAppUtil_stub", "-lSceCtrl_stub", "-lSceTouch_stub", "-lSceAudio_stub",
    "-lScePower_stub", "-lSceRtc_stub", "-lSceSysmodule_stub", "-lSceLibKernel_stub",
]


def rel(p):
    return os.path.relpath(p, ROOT).replace(" ", "$ ")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--with-game", action="store_true", help="link the decomp's game code")
    ap.add_argument("--decomp", default=str(ROOT / "build" / "decomp"),
                    help="build tree: the decomp with the port patch applied (see setup.sh)")
    ap.add_argument("--rom", default=os.environ.get("KH_ROM", str(ROOT.parent / "days.nds")),
                    help="the EU dump; only its overlay table is read (addresses, no content)")
    args = ap.parse_args()

    version = (ROOT / "VERSION").read_text().strip()
    major, minor, patch = (version.split(".") + ["0", "0"])[:3]
    app_ver = f"{int(major):02d}.{int(minor) * 10 + int(patch):02d}"

    port_srcs = sorted((ROOT / "platform").rglob("*.c"))
    game_srcs = []
    defines = [f'-DKH_VERSION="{version}"']
    includes = [f"-I{ROOT / 'platform' / 'core'}", f"-I{ROOT / 'platform'}",
                f"-I{ROOT / 'platform' / 'compat'}"]
    game_includes = []
    if args.with_game:
        import decomp_sources
        decomp = Path(args.decomp).resolve()
        if not (decomp / "src").is_dir():
            sys.exit(f"{decomp} is not a decomp tree: run ./setup.sh first")
        game_srcs = decomp_sources.game_sources(decomp)
        rom = Path(args.rom).resolve()
        if not rom.is_file():
            sys.exit(f"{rom}: the EU ROM is needed to read its overlay table (--rom)")
        subprocess.run([sys.executable, str(ROOT / "tools" / "gen_link_support.py"), str(decomp),
                        str(ROOT / "build" / "gen"), str(rom)], check=True)
        defines.append("-DKH_WITH_GAME=1")
        defines_game = ["-Dmain=NitroMain"]
        game_includes = defines_game + [f"-I{ROOT / 'platform' / 'compat'}", f"-I{decomp / 'include'}"]
    else:
        port_srcs = [p for p in port_srcs if "platform/hw" not in p.as_posix()
                     and "platform/nitro" not in p.as_posix()]

    q = lambda xs: " ".join(shlex.quote(str(x)) for x in xs)
    out = []
    w = out.append
    w("# generated by configure_vita.py -- do not edit")
    w("ninja_required_version = 1.10")
    w(f"cc = {BIN / 'arm-vita-eabi-gcc'}")
    w(f"cxx = {BIN / 'arm-vita-eabi-g++'}")
    w(f"ar = {BIN / 'arm-vita-eabi-gcc-ar'}")
    # the version and the game switch only concern the port's code: a new VERSION must not
    # recompile the 24k game sources
    w(f"common = {q(COMMON_CFLAGS)}")
    w(f"port_cflags = {q(PORT_CFLAGS + defines + includes)}")
    w(f"game_cflags = {q(GAME_CFLAGS + game_includes)}")
    w(f"game_cxxflags = {q(GAME_CXXFLAGS + game_includes)}")
    w(f"libs = {q(LIBS)}")
    w("")
    w("rule cc_port\n  command = $cc $common $port_cflags -MMD -MF $out.d -c $in -o $out\n"
      "  depfile = $out.d\n  deps = gcc\n  description = CC $in")
    w("rule cxx_game\n  command = $cxx $common $game_cxxflags -MMD -MF $out.d -c $in -o $out\n"
      "  depfile = $out.d\n  deps = gcc\n  description = CXX $in")
    w("rule as_game\n  command = $cc $common -c $in -o $out\n  description = AS $in")
    w("rule cc_game\n  command = $cc $common $game_cflags -MMD -MF $out.d -c $in -o $out\n"
      "  depfile = $out.d\n  deps = gcc\n  description = CC $in")
    # One archive per game module: ld keeps every input open, and 24k objects exceed the
    # host's file limit. --whole-archive keeps all of it, as the DS build had it;
    # --gc-sections then drops what nothing reaches.
    # tools/weaken_unowned.py keeps delinks.txt's section ownership (see its docstring)
    w(f"rule ar\n  command = python3 tools/weaken_unowned.py {shlex.quote(str(Path(args.decomp).resolve()))}"
      " $out $in\n  description = AR $out")
    w("rule as\n  command = $cc $common -c $in -o $out\n  description = AS $in")
    w("rule link\n  command = $cc -Wl,-q -Wl,--gc-sections -Wl,--no-enum-size-warning $link_extra"
      " $port_objs -Wl,--whole-archive $game_libs -Wl,--no-whole-archive $libs -o $out\n"
      "  description = LINK $out")
    w(f"rule velf\n  command = {BIN / 'vita-elf-create'} $in $out\n  description = VELF $out")
    w(f"rule fself\n  command = {BIN / 'vita-make-fself'} -c $in $out\n  description = FSELF $out")
    w(f"rule sfo\n  command = {BIN / 'vita-mksfoex'} -s TITLE_ID={TITLE_ID} -s APP_VER={app_ver}"
      f" -d ATTRIBUTE2=12 {shlex.quote(TITLE)} $out\n  description = SFO $out")
    w(f"rule livearea\n  command = python3 {rel(ROOT / 'tools' / 'make_livearea.py')} sce_sys\n"
      "  description = LIVEAREA")
    w(f"rule vpk\n  command = {BIN / 'vita-pack-vpk'} -s build/param.sfo -b build/eboot.bin"
      " -a sce_sys/icon0.png=sce_sys/icon0.png"
      " -a sce_sys/livearea/contents/bg.png=sce_sys/livearea/contents/bg.png"
      " -a sce_sys/livearea/contents/startup.png=sce_sys/livearea/contents/startup.png"
      " -a sce_sys/livearea/contents/template.xml=sce_sys/livearea/contents/template.xml"
      " $out\n  description = VPK $out")
    w("")

    objs = []
    for src in port_srcs:
        obj = "build/port/" + os.path.relpath(src, ROOT)[:-2] + ".o"
        w(f"build {obj}: cc_port {rel(src)}")
        objs.append(obj)
    modules = {}
    if game_srcs:
        import decomp_sources
        decomp = Path(args.decomp).resolve()
        rule = {"c": "cc_game", "cpp": "cxx_game", "s": "as_game"}
        for src, kind in game_srcs:
            relsrc = os.path.relpath(src, decomp)
            obj = "build/game/" + os.path.splitext(relsrc)[0] + ".o"
            w(f"build {obj.replace(' ', '$ ')}: {rule[kind]} {str(src).replace(' ', '$ ')}")
            modules.setdefault(decomp_sources.module_of(relsrc), []).append(obj)
    link_extra = ""
    if game_srcs:
        w("build build/gen/ds_bss.o: as build/gen/ds_bss.S")
        w("build build/gen/overlays.o: cc_port build/gen/overlays.c")
        objs += ["build/gen/ds_bss.o", "build/gen/overlays.o"]
        # the shared area's named words (platform/hw/shared_area.c)
        link_extra = ("@build/gen/link.rsp -Wl,-T,build/gen/overlays.ld"
                      " -Wl,--defsym=data_027ffff0=kh_ds_shared_area+0xff0")
    game_libs = []
    for name, mobjs in sorted(modules.items()):
        lib = f"build/lib/{name}.a"
        w(f"build {lib}: ar {' '.join(mobjs)} | build/gen/bss_names.txt tools/weaken_unowned.py")
        game_libs.append(lib)

    art = ["sce_sys/icon0.png", "sce_sys/livearea/contents/bg.png",
           "sce_sys/livearea/contents/startup.png"]
    vpk = f"build/khdays-vita-{version}.vpk"
    w("")
    w(f"build build/khdays.elf: link {' '.join(objs + game_libs)}")
    w(f"  port_objs = {' '.join(objs)}")
    w(f"  game_libs = {' '.join(game_libs)}")
    w(f"  link_extra = {link_extra}")
    w("build build/khdays.velf: velf build/khdays.elf")
    w("build build/eboot.bin: fself build/khdays.velf")
    w("build build/param.sfo: sfo | VERSION")
    w(f"build {' '.join(art)}: livearea")
    w(f"build {vpk}: vpk build/eboot.bin build/param.sfo {' '.join(art)}"
      " sce_sys/livearea/contents/template.xml")
    w(f"default {vpk}")
    (ROOT / "build.ninja").write_text("\n".join(out) + "\n")
    print(f"build.ninja: {len(port_srcs)} port + {len(game_srcs)} game sources -> {vpk}")


if __name__ == "__main__":
    main()
